Attribute VB_Name = "SCEx"
Option Explicit

'*/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/
'*
'* [機能名] MSScriptControlラップ・拡張モジュール
'* [詳  細] MSScriptControlのWrapperとしての機能を提供する他、MSScriptControl
'*          を使用したユーティリティを提供する。
'*          ラップするMSScriptControlライブラリは以下のものとする。
'*              [name] Microsoft Script Control 1.0
'*              [dll] C:\Windows\SysWOW64\msscript.ocx
'* [参  考]
'*  Microsoftの公式情報が見つからない。
'*  <https://developpaper.com/introduction-of-msscriptcontrol-scriptcontrol-component-properties-methods-and-events/>
'*  <https://developpaper.com/examples-of-usage-of-msscriptcontrol-scriptcontrol-components/>
'*  <https://news.mynavi.jp/article/20120325-vba/2>
'*  <https://www.slideshare.net/satoshiohya/vba-62341558>
'*
'* [注  意]
'*  MSScriptControlは基本的には32bit環境のみで使用できるライブラリ。
'*  32bit互換実行のWsh経由で取得したオブジェクトを使用しているため、生成に
'*  時間がかかる上、動作が不安定。
'*
'* @author Bankura
'* Copyright (c) 2019 Bankura
'*/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/


'******************************************************************************
'* 定数定義
'******************************************************************************
'*-----------------------------------------------------------------------------
'* Module ScriptControlConstants.GlobalModule
'* Name of built-in global module - can be used as an index in ScriptControl.Modules.
'*-----------------------------------------------------------------------------
Public Const GlobalModule = "Global"

'*-----------------------------------------------------------------------------
'* Module ScriptControlConstants.NoTimeout
'* Setting ScriptControl.Timeout to this value prevents timeout check from occurring.
'*-----------------------------------------------------------------------------
Public Const NoTimeout = -1

'******************************************************************************
'* Enum定義
'******************************************************************************
'*-----------------------------------------------------------------------------
'* ScriptControlStates
'* States into which the scripting engine can be placed.
'*-----------------------------------------------------------------------------
Public Enum ScriptControlStates
    Connected = 1    'Engine will execute code and sink events generated by objects added with ScriptControl.AddObject
    Initialized = 0  'Engine will execute code but will not sink events generated by objects added with ScriptControl.AddObject
End Enum

'******************************************************************************
'* メソッド定義
'******************************************************************************


